### ISSUE TITLE
libxpparam.so,libxpdepth.so. 

### ISSUE THREAD

**Issue by hlcool** [baidu/boteye_driver#2]
Hi :
when  I  use these two libs, I have such a problem. please help me， 3Q

cooper@cooper:~/Development/boteye_driver/app/libs$ ldd libxpdepth.so 
	linux-vdso.so.1 =>  (0x00007ffd32dee000)
	libglog.so.0 => /usr/lib/x86_64-linux-gnu/libglog.so.0 (0x00007fa327abd000)
	libopencv_calib3d.so.3.0 => not found
	libopencv_imgproc.so.3.0 => not found
	libopencv_core.so.3.0 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa32773a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa327430000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa32721a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa326e50000)
	libgflags.so.2 => /usr/lib/x86_64-linux-gnu/libgflags.so.2 (0x00007fa326c2e000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007fa326a13000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa3267f6000)
	/lib64/ld-linux-x86-64.so.2 (0x00005589ba1ad000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fa3265d3000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa3263cf000)
cooper@cooper:~/Development/boteye_driver/app/libs$ ldd libxpparam.so 
	linux-vdso.so.1 =>  (0x00007ffe3d6b1000)
	libopencv_calib3d.so.3.0 => not found
	libglog.so.0 => /usr/lib/x86_64-linux-gnu/libglog.so.0 (0x00007f2c0e454000)
	libyaml-cpp.so.0.5 => /usr/lib/x86_64-linux-gnu/libyaml-cpp.so.0.5 (0x00007f2c0e1d7000)
	libopencv_imgproc.so.3.0 => not found
	libopencv_core.so.3.0 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2c0de54000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2c0dc3d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2c0d873000)
	libgflags.so.2 => /usr/lib/x86_64-linux-gnu/libgflags.so.2 (0x00007f2c0d652000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f2c0d436000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2c0d219000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2c0cf10000)
	/lib64/ld-linux-x86-64.so.2 (0x0000558cfff40000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f2c0cced000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2c0cae9000)

**Comment by HansomHu** [comment]
Have you installed opencv libraries ? What's the kernel version of ubuntu?
